[package]
name = "les_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"
globset = "0.4"
regex = "1"
bincode = "1.3"
sled = "0.34"
chrono = { version = "0.4", features = ["serde"] }
